Repository storefront-x/storefront-x, pull requests merged in 2022-12, with the labels that each got.

#232 Improve caching of static assets
  modules/base-commerce/server/routes/_i.js
  modules/core/src/Serve.js
Labels: internal

#229 Add basic support for Google Analytics
  modules/core/sfx.js
  modules/demo-magento/config/googleAnalytics/GOOGLE_ANALYTICS_ID.ts
  modules/demo-shopware/config/googleAnalytics/GOOGLE_ANALYTICS_ID.ts
  modules/google-analytics/config/googleAnalytics/GOOGLE_ANALYTICS_ID.ts
  modules/google-analytics/package.json
  modules/google-analytics/vue/plugins/googleAnalytics.server.ts
  storefront-x.config.js
  storefront-x.magento.config.js
  storefront-x.shopware.config.js
  yarn.lock
Labels: enhancement

#234 Add documentation and tests for Google Analytics
  docs/.vitepress/config.js
  docs/modules/google-analytics.md
  modules/base-commerce/tests/playwright/ModuleCombinations.spec.js
  modules/google-analytics/config/googleAnalytics/GOOGLE_ANALYTICS_ID.ts
  modules/google-analytics/tests/playwright/GoogleAnalytics.spec.js
  modules/google-analytics/tests/playwright/ModuleCombinations.spec.js
  modules/google-tag-manager-partytown/tests/playwright/ModuleCombinations.spec.js
  modules/google-tag-manager/tests/playwright/ModuleCombinations.spec.js
  modules/theme-tailwind/tests/playwright/ModuleCombinations.spec.js
Labels: documentation
