Repository storefront-x/storefront-x, pull requests merged in 2023-02, with the labels that each got.

#310 Add static pages to the sitemap
  modules/sitemap/server/routes/sitemap.xml.ts
  modules/vue-router-simple/sitemap/staticPages.ts
  modules/vue-router/sitemap/staticPages.ts
Labels: enhancement

#301 Disable Google analytics on demos
  modules/demo-px/config/googleAnalytics/GOOGLE_ANALYTICS_ID.ts
  modules/demo-shopware/config/googleAnalytics/GOOGLE_ANALYTICS_ID.ts
  storefront-x.px.config.js
  storefront-x.shopware.config.js
Labels: internal

#312 Limit allowed branch names
  .husky/pre-commit
Labels: internal

#313 Fix checkout hydration error
  modules/cart/composables/useCart.ts
  modules/theme-tailwind-magento/templates/Checkout.vue
  modules/theme-tailwind/molecules/MicroCart.vue
Labels: bug

#250 Purge old Cypress files during bootstrap
  modules/core/src/Concept.js
  modules/core/src/CopyingConcept.js
  modules/core/src/GeneratingConcept.js
  modules/core/src/OverridingConcept.js
  modules/cypress/concepts/CypressIntegration.js
  modules/cypress/concepts/CypressPageObjects.js
  modules/cypress/concepts/CypressRepositories.js
Labels: internal

#297 Add tooling module
  .github/workflows/core.yml
  .husky/pre-commit
  modules/cypress/package.json
  modules/testing/package.json
  modules/tooling/package.json
  package.json
  yarn.lock
Labels: enhancement

#314 Fix timeout in waitForStore
  modules/vue-pinia/utils/vuePinia/waitForStore.ts
Labels: bug

#316 Fix checkout not loading for signed in customers
  modules/cart-magento/magento/errorHandlers/handleInvalidCart.ts
  modules/cart-magento/services/useGetCart.ts
  modules/cart-magento/services/useGetCartId.ts
  modules/cart-magento/services/useGetCustomerCartId.ts
  modules/cart-magento/services/useGetOrCreateCartId.ts
  modules/cart-magento/services/useMergeCarts.ts
  modules/cart-magento/stores/useCartMagentoStore.clientInit.ts
  modules/cart-magento/stores/useCartMagentoStore.ts
  modules/checkout-magento/services/usePlaceOrder.ts
  modules/customer-magento/services/useGetCartId.ext.ts
  modules/customer-magento/services/useLogoutCustomer.ts
  modules/demo-px/cypress/integration/account.js
Labels: bug

#300 Improve docs for create script
  docs/getting-started/quick-start.md
  docs/integrations/magento.md
  modules/create-storefront-x/index.js
Labels: documentation

#318 Add NProgress to optimizeDeps
  modules/nprogress/vite.config.js
Labels: bug

#319 Add removeFields GraphQL util
  modules/graphql/tests/unit/utils/graphql/removeFields.spec.js
  modules/graphql/utils/graphql/removeFields.ts
Labels: enhancement

#322 Add support for type extensions
  modules/base/concepts/Types.js
  modules/demo-magento/config/VUE_I18N_LOCALES.ts
  modules/demo-px/config/VUE_I18N_LOCALES.ts
  modules/demo-shopware/config/VUE_I18N_LOCALES.ts
  modules/magento/types/vue-i18n/Locale.ext.ts
  modules/shopware/types/vue-i18n/Locale.ext.ts
  modules/theme-blank/config/VUE_I18N_LOCALES.ts
  modules/theme-blank/config/VUE_I18N_ROUTE_PATHS.ts
  modules/theme-blank/package.json
  modules/theme-blank/pages/cart.vue
  modules/theme-blank/pages/index.vue
  modules/theme-tailwind/types/vue-i18n/Locale.ext.ts
  modules/vue-i18n/types/vue-i18n/Locale.ts
  yarn.lock
Labels: enhancement

#323 Fix casing of goToWishlist
  modules/create-storefront-x/template/magento/modules/demo-magento/cypress/integration/wishlist.js
  modules/create-storefront-x/template/px/modules/demo-px/cypress/integration/wishlist.js
  modules/demo-magento/cypress/integration/wishlist.js
  modules/demo-px/cypress/integration/wishlist.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/base/gotoWishList.js
Labels: internal

#317 Add Vite section to the docs
  docs/assets/images/vite-logo.svg
  docs/getting-started/introduction.md
Labels: documentation

#327 Fix typos in the documentation
  docs/getting-started/how-it-works.md
  docs/getting-started/simple-todo-app.md
Labels: documentation

#329 Make cookie-auth return non 200 statuses
  modules/cookie-auth/pages/cookie-auth/$layout.vue
  modules/cookie-auth/server/middleware/cookieAuth.ts
  modules/cookie-auth/tests/playwright/CookieAuth.spec.js
  modules/theme-tailwind/cypress/support/pageObjects/base/goToWishlist.js
Labels: bug

#330 Add header bypass to cookie-auth
  docs/modules/cookie-auth.md
  modules/cookie-auth/config/cookieAuth/fallbackHeaderName.ts
  modules/cookie-auth/server/middleware/cookieAuth.ts
  modules/cookie-auth/tests/playwright/CookieAuth.spec.js
Labels: enhancement

#331 Fix ServiceWorker caching
  docs/advanced/pwa.md
  modules/demo-magento/vite.config.js
  modules/demo-px/vite.config.js
  modules/demo-shopware/vite.config.js
Labels: bug

#325 Add 'sfx make' command
  .yarn/cache/kolorist-npm-1.7.0-6b162a4835-0eb64d22a2.zip
  docs/cookbook/create-new-module.md
  modules/core/make/module.js
  modules/core/package.json
  modules/core/sfx.js
  package.json
  yarn.lock
Labels: enhancement

#332 Fix TypeScript aliases for modules in node_modules
  modules/create-storefront-x/template/blank/tsconfig.json
  modules/create-storefront-x/template/magento/tsconfig.json
  modules/create-storefront-x/template/px/tsconfig.json
  modules/create-storefront-x/template/shopware/tsconfig.json
Labels: bug

#335 Move brand field to the Product fragment extension
  modules/brands-magento/graphql/fragments/Product.ext.ts
  modules/brands-magento/graphql/queries/ProductDetail.ext.ts
Labels: bug

#326 Shard Playwright tests
  .github/workflows/core.yml
  .github/workflows/cypress.yml
Labels: internal

#334 Add bad-credentials status to failed cookie auth redirect
  modules/cookie-auth/server/middleware/cookieAuth.ts
Labels: enhancement

#339 Fix urlSuffix on Product and Category
  modules/catalog-magento/composables/useCategory.ts
  modules/catalog-magento/composables/useProduct.ts
  modules/catalog-magento/graphql/fragments/CategoryTree.ts
  modules/catalog-magento/graphql/fragments/Product.ts
  modules/catalog-magento/graphql/fragments/ProductInListing.ts
  modules/catalog-magento/graphql/queries/Categories.ts
  modules/catalog-magento/graphql/queries/CategoryDetail.ts
  modules/catalog-magento/graphql/queries/CategoryList.ts
  modules/catalog-magento/mappers/ToCategory.ts
  modules/catalog-magento/mappers/ToProduct.ts
  modules/theme-tailwind-magento/cypress/support/pageObjects/product/visitAgain.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/product/visitRandom.js
Labels: bug

#340 Fix i18n datetimes to not crash with null
  modules/vue-i18n/composables/useI18n.ts
  modules/vue-i18n/tests/playwright/I18nDatetimes.spec.js
Labels: bug

#343 Support newsletter double opt-in trough email link
  modules/demo-magento/pages/newsletter/subscriber/confirm/id/[id]/code/[code]/index.vue
  modules/demo-px/pages/newsletter/subscriber/confirm/id/[id]/code/[code]/index.vue
  modules/newsletter-magento/graphql/mutations/ConfirmSubscribeEmailToNewsletter.ts
  modules/newsletter-magento/graphql/mutations/SubscribeEmailToNewsletter.ts
  modules/newsletter-magento/package.json
  modules/newsletter-magento/repositories/useConfirmSubscribeEmailToNewsletterRepository.ts
  modules/newsletter-magento/repositories/useSubscribeEmailToNewsletterRepository.ts
  modules/newsletter-magento/services/useConfirmSubscriptionToNewsletter.ts
  modules/newsletter-magento/services/useSubscribeToNewsletter.ts
  modules/theme-tailwind-magento/molecules/Newsletter.vue
  modules/theme-tailwind/templates/ThankYouSubscribeNewsletter.vue
  modules/vue-router-simple/concepts/Pages.js
  modules/vue-router-simple/tests/playwright/Params.spec.js
  storefront-x.magento.config.js
  storefront-x.px.config.js
  yarn.lock
Labels: enhancement

#344 Fix cookies to be set on root path
  modules/customer-magento/composables/useCustomerToken.ts
  modules/magento/magento/afterResponse/useGetCacheId.ts
Labels: bug

#337 Set common build step for GitHub CI workflows
  .github/workflows/core.yml
  .github/workflows/cypress.yml
  .github/workflows/lighthouse.yml
  .github/workflows/lint.yml
  .github/workflows/magento.yml
  .github/workflows/px.yml
  .github/workflows/shopware.yml
  .github/workflows/unit.yml
  .github/workflows/yarn.yml
Labels: internal

#345 Dead-code eliminate bus emitters without listeners
  modules/cart-magento/services/useAddToCart.ts
  modules/core/src/Core.js
  modules/vue/concepts/BusEmitters.js
  modules/vue/tests/playwright/EventBus.spec.js
Labels: internal

#341 Add support for runtime config
  docs/.vitepress/config.js
  docs/modules/runtime-config.md
  modules/runtime-config/concepts/RuntimeConfig.js
  modules/runtime-config/package.json
  modules/runtime-config/tests/playwright/RuntimeConfig.spec.js
  modules/runtime-config/utils/getRuntimeConfigValue.ts
  modules/runtime-config/vue/plugins/runtimeConfig.server.ts
  yarn.lock
Labels: enhancement

#346 Add option to set Sentry environment
  docs/modules/sentry.md
  modules/base/config/ENVIRONMENT.ts
  modules/sentry-client/config/sentry/client/environment.ts
  modules/sentry-client/vue/plugins/sentry.client.ts
  modules/sentry-server/config/sentry/server/environment.ts
  modules/sentry-server/server/startup/sentry.ts
Labels: enhancement

#338 Create Cypress videos and screenshots for failed tests
  cypress.config.ts
Labels: internal

#348 Retry MxCloud deploy on failure
  .github/workflows/mxcloud.yml
Labels: internal

#349 Log MagentoError in dev mode
  modules/base-commerce/vue/providers/ErrorHandlersProvider.server.vue
  modules/core/sfx.js
  modules/magento/tests/playwright/MagentoErrors.spec.js
  modules/magento/vue/errorHandlers/handleMagentoError.ts
  modules/vue-pinia/utils/vuePinia/waitForStore.ts
Labels: enhancement

#351 Fix CMS pages in demo/px
  modules/demo-px/magento/dynamicPages/CMS_PAGE.vue
Labels: bug

#356 Publish docs on GitHub Pages
  .github/workflows/deploy.yml
Labels: internal

#357 Fix data mapping for password reset
  modules/customer-magento/repositories/useChangeCustomerPasswordRepository.ts
Labels: bug

#353 Improve testing of create-script module
  .github/workflows/core.yml
  .github/workflows/release.yml
  modules/create-storefront-x/template/blank/storefront-x.config.js
  modules/create-storefront-x/template/px/modules/demo-px/config/GOOGLE_API_KEY.ts
  modules/create-storefront-x/template/px/package.json
  modules/product-comparison/composables/useComparison.ts
  modules/product-comparison/package.json
  modules/product-comparison/stores/useProductComparisonStore.ts
  yarn.lock
Labels: internal

#358 Add support for Product Grid in PB product component
  modules/cms-magento/composables/usePbProducts.ts
  modules/theme-tailwind-magento/magento/cms/blocks/pb-products.vue
  modules/theme-tailwind/organisms/ProductGrid.vue
  modules/theme-tailwind/organisms/ProductListing.vue
Labels: enhancement

#361 Upgrade deps
  modules/base-commerce/package.json
  modules/braintree/package.json
  modules/cms-magento/package.json
  modules/core/package.json
  modules/create-storefront-x/package.json
  modules/create-storefront-x/template/blank/tsconfig.json
  modules/create-storefront-x/template/magento/modules/demo-magento/package.json
  modules/create-storefront-x/template/magento/tsconfig.json
  modules/create-storefront-x/template/px/modules/demo-px/base/templates/index.html
  modules/create-storefront-x/template/px/modules/demo-px/package.json
  modules/create-storefront-x/template/px/tsconfig.json
  modules/create-storefront-x/template/shopware/modules/demo-shopware/package.json
  modules/create-storefront-x/template/shopware/tsconfig.json
  modules/magento/services/useSwitchToStore.ts
  modules/runtime-config/utils/getRuntimeConfigValue.ts
  modules/sentry-client/package.json
  modules/sentry-server/package.json
  modules/shopware/services/useSwitchToStore.ts
  modules/testing/package.json
  modules/theme-tailwind/package.json
  modules/tooling/package.json
  modules/vue-head/package.json
  modules/vue-i18n/package.json
  modules/vue-pinia/package.json
  modules/vue/package.json
  package.json
  yarn.lock
Labels: internal

#359 Cancel old workflows
  .github/workflows/core.yml
  .github/workflows/docs.yml
  .github/workflows/magento.yml
  .github/workflows/px.yml
  .github/workflows/release.yml
  .github/workflows/shopware.yml
Labels: internal

#355 Add support for PageBuilder dynamic blocks
  modules/cms-magento/composables/cms/usePbBanner.ts
  modules/cms-magento/composables/cms/usePbBlock.ts
  modules/cms-magento/composables/cms/usePbButtonItem.ts
  modules/cms-magento/composables/cms/usePbButtons.ts
  modules/cms-magento/composables/cms/usePbColumn.ts
  modules/cms-magento/composables/cms/usePbDivider.ts
  modules/cms-magento/composables/cms/usePbDynamicBlock.ts
  modules/cms-magento/composables/cms/usePbHeading.ts
  modules/cms-magento/composables/cms/usePbHtml.ts
  modules/cms-magento/composables/cms/usePbImage.ts
  modules/cms-magento/composables/cms/usePbProducts.ts
  modules/cms-magento/composables/cms/usePbRow.ts
  modules/cms-magento/composables/cms/usePbSlider.ts
  modules/cms-magento/composables/cms/usePbText.ts
  modules/cms-magento/composables/cms/usePbVideo.ts
  modules/cms-magento/graphql/queries/CmsDynamicBlock.ts
  modules/cms-magento/mappers/ToCmsDynamicBlock.ts
  modules/cms-magento/repositories/useGetCmsDynamicBlockByIdRepository.ts
  modules/cms/services/useGetCmsDynamicBlockById.ts
  modules/theme-tailwind-magento/magento/cms/blocks/pb-banner.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-button-item.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-buttons.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-column-group.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-column-line.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-column.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-divider.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-dynamic_block.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-heading.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-html.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-image.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-products.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-row.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-slide.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-slider.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-text.vue
  modules/theme-tailwind-magento/magento/cms/blocks/pb-video.vue
  modules/vue/directives/vIntersectionObserver.ts
  modules/vue/package.json
  yarn.lock
Labels: enhancement

#364 Remove old usePbProducts composable
  modules/cms-magento/composables/cms/usePbProducts.ts
  modules/cms-magento/composables/usePbProducts.ts
Labels: bug

#360 Improve PWA functionalities
  docs/.vitepress/config.js
  docs/advanced/pwa.md
  docs/modules/service-worker.md
  docs/modules/web-app-manifest.md
  modules/base-commerce/serviceWorker/runtimeCache/_i.js
  modules/core/src/Build.js
  modules/core/src/Concept.js
  modules/create-storefront-x/template/magento/modules/demo-magento/base/templates/index.html
  modules/create-storefront-x/template/magento/modules/demo-magento/package.json
  modules/create-storefront-x/template/magento/modules/demo-magento/vite.config.js
  modules/create-storefront-x/template/magento/modules/demo-magento/webAppManifest/description.ts
  modules/create-storefront-x/template/magento/modules/demo-magento/webAppManifest/icons.ts
  modules/create-storefront-x/template/magento/modules/demo-magento/webAppManifest/name.ts
  modules/create-storefront-x/template/magento/package.json
  modules/create-storefront-x/template/magento/storefront-x.config.js
  modules/create-storefront-x/template/px/modules/demo-px/base/templates/index.html
  modules/create-storefront-x/template/px/modules/demo-px/package.json
  modules/create-storefront-x/template/px/modules/demo-px/vite.config.js
  modules/create-storefront-x/template/px/modules/demo-px/webAppManifest/description.ts
  modules/create-storefront-x/template/px/modules/demo-px/webAppManifest/icons.ts
  modules/create-storefront-x/template/px/modules/demo-px/webAppManifest/name.ts
  modules/create-storefront-x/template/px/package.json
  modules/create-storefront-x/template/px/storefront-x.config.js
  modules/magento/serviceWorker/runtimeCache/_magento.js
  modules/service-worker/concepts/ServiceWorkerRuntimeCache.js
  modules/service-worker/package.json
  modules/service-worker/tests/playwright/ServiceWorker.spec.js
  modules/service-worker/vue/plugins/ServiceWorker.client.ts
  modules/theme-tailwind/webAppManifest/background_color.ts
  modules/theme-tailwind/webAppManifest/description.ts
  modules/theme-tailwind/webAppManifest/display.ts
  modules/theme-tailwind/webAppManifest/icons.ts
  modules/theme-tailwind/webAppManifest/name.ts
  modules/theme-tailwind/webAppManifest/scope.ts
  modules/theme-tailwind/webAppManifest/short_name.ts
  modules/theme-tailwind/webAppManifest/start_url.ts
  modules/theme-tailwind/webAppManifest/theme_color.ts
  modules/web-app-manifest/concepts/WebAppManifest.js
  modules/web-app-manifest/package.json
  modules/web-app-manifest/server/routes/manifest.webmanifest.ts
  modules/web-app-manifest/tests/playwright/WebAppManifest.spec.js
  modules/web-app-manifest/vue/plugins/Manifest.server.ts
  modules/web-app-manifest/webAppManifest/$schema.ts
  yarn.lock
Labels: enhancement

#365 Fix duplicated carousel in pb-products
  modules/theme-tailwind-magento/magento/cms/blocks/pb-products.vue
Labels: bug

#367 Add names to GraphQL requests
  modules/base-commerce/concepts/GqlFragments.js
  modules/base-commerce/concepts/GqlMutations.js
  modules/base-commerce/concepts/GqlQueries.js
  modules/graphql/GraphQL.js
  modules/graphql/concepts/Graphql.js
  modules/graphql/concepts/GraphqlFragments.js
  modules/graphql/concepts/GraphqlMutations.js
  modules/graphql/concepts/GraphqlQueries.js
  modules/graphql/tests/unit/graphql/mutation.spec.js
  modules/graphql/tests/unit/graphql/query.spec.js
Labels: enhancement

#366 Improve performance by removing blocking scripts and SW asset caching
  modules/cookie-script/vue/plugins/cookieScript.server.ts
  modules/service-worker/concepts/ServiceWorkerRuntimeCache.js
  modules/service-worker/tests/playwright/ServiceWorker.spec.js
Labels: enhancement

#368 Add request-profiler module
  modules/core/sfx.js
  modules/create-storefront-x/template/magento/storefront-x.config.js
  modules/create-storefront-x/template/px/storefront-x.config.js
  modules/magento/composables/useMagento.ts
  modules/request-profiler/magento/afterResponse/requestProfiler.server.ts
  modules/request-profiler/magento/beforeRequest/requestProfiler.server.ts
  modules/request-profiler/package.json
  modules/request-profiler/vue/plugins/requestProfiler.server.ts
  yarn.lock
Labels: enhancement

#369 Improve create script testing
  .github/workflows/core.yml
  modules/core/sfx.js
  modules/create-storefront-x/template/magento/package.json
  modules/create-storefront-x/template/px/package.json
Labels: internal

#370 Error notifications no longer hide automatically
  modules/base-commerce/composables/useShowErrorNotification.ts
  modules/base-commerce/composables/useShowNotification.ts
Labels: enhancement

#371 Handle unhandledrejection events
  modules/base-commerce/vue/providers/ErrorHandlersProvider.client.vue
Labels: enhancement

#372 Move error handling to top level error handlers
  modules/cart-magento/magento/errorHandlers/handleInvalidCart.ts
  modules/customer-magento/magento/errorHandlers/handleAuthorizationError.ts
  modules/theme-tailwind/vue/errorHandlers/handleCartResetted.ts
  modules/theme-tailwind/vue/errorHandlers/handleCustomerNotAuthorized.ts
Labels: enhancement

#373 Add docs for request profiler
  docs/.vitepress/config.js
  docs/modules/request-profiler.md
Labels: documentation

#374 Improve typing of useResource
  modules/vue/composables/useResource.ts
Labels: enhancement

#375 Fix typing of useRoute
  modules/vue-router/composables/useRoute.ts
Labels: bug

#377 Add messages to thrown errors
  modules/cart-magento/magento/errorHandlers/handleInvalidCart.ts
  modules/customer-magento/magento/errorHandlers/handleAuthorizationError.ts
  modules/magento/utils/graphql/isInvalidCart.ts
Labels: enhancement

#382 Add support for verbose request profiler
  docs/modules/request-profiler.md
  modules/request-profiler/config/requestProfiler/verbose.ts
  modules/request-profiler/vue/plugins/requestProfiler.server.ts
Labels: enhancement

#380 Optimize fetching of BlogGrid on HP
  modules/create-storefront-x/template/px/modules/demo-px/pages/index.vue
  modules/theme-tailwind/molecules/BlogGrid.vue
  modules/vue/composables/useResource.ts
Labels: enhancement

#385 Disable CSS code splitting
  modules/theme-tailwind/vite.config.js
Labels: internal

#386 Fix async attr in cookie script
  modules/cookie-script/vue/plugins/cookieScript.server.ts
Labels: bug
