Repository storefront-x/storefront-x, pull requests merged in 2023-01, with the labels that each got.

#239 Update service worker with new releases
  docs/general/pwa.md
  modules/demo-magento/vite.config.js
  modules/demo-shopware/vite.config.js
  modules/demo-venia/vite.config.js
Labels: bug

#241 Add useSetResponseStatus composable
  .github/workflows/core.yml
  docs/modules/vue.md
  modules/theme-tailwind/templates/NotFound.vue
  modules/vue/composables/useSetResponseStatus.ts
  modules/vue/tests/playwright/useSetResponseStatus.spec.js
Labels: enhancement

#242 Allow overriding of create-script prompts with argument flags
  modules/atatus/config/ATATUS_RUM_API_KEY.ts
  modules/base-commerce/config/GOOGLE_API_KEY.ts
  modules/basic-auth/config/BASIC_AUTH.ts
  modules/cookie-script/config/COOKIE_SCRIPT_ID.ts
  modules/create-storefront-x/index.js
  modules/create-storefront-x/template/magento/modules/demo-magento/config/GOOGLE_API_KEY.ts
  modules/create-storefront-x/template/shopware/modules/demo-shopware/config/GOOGLE_API_KEY.ts
  modules/create-storefront-x/template/venia/modules/demo-venia/config/GOOGLE_API_KEY.ts
  modules/google-tag-manager/config/GOOGLE_TAG_MANAGER_ID.ts
  modules/magento/config/MAGENTO_URL.ts
  modules/shopware/config/SHOPWARE_ACCESS_KEY.ts
  modules/shopware/config/SHOPWARE_URL.ts
  modules/vue-i18n/config/VUE_I18N_LOCALES.ts
Labels: enhancement

#243 Fix create script
  .github/workflows/core.yml
  .github/workflows/magento.yml
  .github/workflows/shopware.yml
  .github/workflows/venia.yml
  docs/modules/vue-pinia.md
  modules/base-commerce/stores/useNotificationStore.ts
  modules/base-commerce/stores/useStoreStore.ts
  modules/cart-magento/stores/useCartMagentoStore.ts
  modules/cart-shopware/stores/useCartShopwareStore.ts
  modules/cart/stores/useCartStore.ts
  modules/catalog-magento/stores/useCatalogMagentoStore.ts
  modules/catalog-shopware/stores/useCatalogShopwareStore.ts
  modules/catalog/stores/useCatalogStore.ts
  modules/checkout-shopware/stores/useCheckoutShopwareStore.ts
  modules/checkout/stores/useCheckoutStore.ts
  modules/create-storefront-x/template/shopware/package.json
  modules/customer-magento/stores/useCustomerMagentoStore.ts
  modules/customer-shopware/stores/useCustomerShopwareStore.ts
  modules/customer/stores/useCustomerStore.ts
  modules/free-shipping-magento/stores/useFreeShippingMagentoStore.ts
  modules/free-shipping/stores/useFreeShippingStore.ts
  modules/magento/stores/useMagentoStore.ts
  modules/multicurrency-magento/stores/useMulticurrencyMagentoStore.ts
  modules/multicurrency-shopware/stores/useMulticurrencyShopwareStore.ts
  modules/multicurrency/stores/useMulticurrencyStore.ts
  modules/robots-magento/stores/useRobotsMagentoStore.ts
  modules/robots/stores/useRobotsStore.ts
  modules/shopware/stores/useShopwareStore.ts
  modules/theme-tailwind/organisms/HamburgerMenu.vue
  modules/theme-tailwind/stores/useThemeTailwindStore.ts
  modules/vue-pinia/tests/playwright/ServerInit.spec.js
  modules/vue-pinia/tests/playwright/Stores.spec.js
  modules/vue-pinia/tests/playwright/VuePinia.spec.js
  modules/vue-pinia/utils/vuePinia/defineStore.ts
  modules/vue-pinia/utils/vuePinia/mapState.ts
  modules/vue-pinia/utils/vuePinia/storeToRefs.ts
  modules/wishlist-magento/stores/useWishlistMagentoStore.ts
  modules/wishlist/composables/useWishlist.ts
  modules/wishlist/stores/useWishlistStore.ts
Labels: internal

#244 Test create script in pipelines
  .github/workflows/core.yml
Labels: internal

#247 Use TypeScript for IoC generated files
  docs/modules/base-commerce.md
  modules/base-commerce/tests/unit/components/SfxCarousel.spec.js
  modules/base-commerce/tests/unit/components/SfxForm.spec.js
  modules/base-commerce/tests/unit/components/SfxImage.spec.js
  modules/base-commerce/tests/unit/components/SfxInput.spec.js
  modules/base-commerce/tests/unit/components/SfxMoney.spec.js
  modules/core/src/IocConcept.js
  modules/nprogress/vue/providers/NprogressProvider.vue
  modules/vue-router/components/SfxLayoutOutlet.vue
  modules/vue/tests/unit/composables/useEventBus.spec.js
Labels: internal

#248 Fix click-through from cart item to product detail on Shopware
  modules/cart-shopware/mappers/ToCartItem.ts
  modules/demo-shopware/pages/$404.vue
  modules/shopware/repositories/useGetSeoUrlRepository.ts
  modules/shopware/services/useUrlResolver.ts
  modules/theme-tailwind-shopware/molecules/OrderSummaryItem.vue
Labels: bug

#186 Add Minicart
  modules/cart/stores/useCartStore.ts
  modules/demo-magento/cypress/integration/miniCart.js
  modules/demo-shopware/cypress/integration/miniCart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/MiniCart.js
  modules/theme-tailwind-shopware/cypress/support/pageObjects/MiniCart.js
  modules/theme-tailwind-shopware/molecules/MiniCartItem.vue
  modules/theme-tailwind/assets/images/cart/no-items-icon.svg
  modules/theme-tailwind/molecules/MicroCart.vue
  modules/theme-tailwind/molecules/MiniCartItem.vue
  modules/theme-tailwind/organisms/MiniCart.vue
Labels: enhancement

#257 Add ToMagentoImage mapper
  modules/base-commerce/concepts/BaseCommerceImageResizer.js
  modules/base-commerce/server/routes/_i.js
  modules/blog-magento/mappers/ToBlogPost.ts
  modules/blog/composables/useBlogPost.ts
  modules/catalog-magento-px/mappers/ToCategory.ext.ts
  modules/magento/baseCommerce/imageResizer/magento.ts
  modules/magento/mappers/ToMagentoImage.ts
Labels: enhancement

#258 Use ToMagentoImage in ToBrand mapper
  modules/brands-magento/mappers/ToBrand.ts
  modules/theme-tailwind-magento/templates/BrandDetail.vue
  modules/theme-tailwind/molecules/HeaderMenu/HamburgerMenuLink.vue
Labels: enhancement

#228 Handle Magento's newsletter errors
  .gitignore
  modules/base-commerce/i18n/messages/cs-CZ.json
  modules/base-commerce/i18n/messages/en-US.json
  modules/base-commerce/vue/providers/ErrorHandlersProvider.client.vue
  modules/base-commerce/vue/providers/ErrorHandlersProvider.server.vue
  modules/magento/composables/useMagento.ts
  modules/magento/errors/MagentoError.ts
  modules/magento/repositories/useSubscribeEmailToNewsletterRepository.ts
  modules/magento/services/useSubscribeToNewsletter.ts
  modules/magento/tests/playwright/MagentoErrors.spec.js
  modules/magento/vue/errorHandlers/handleMagentoError.ts
  modules/theme-tailwind-magento/molecules/Newsletter.vue
  storefront-x.magento.config.js
Labels: enhancement

#226 Add option to reset forgotten password via an email
  modules/customer-magento/graphql/mutations/ResetCustomerPassword.ts
  modules/customer-magento/repositories/useResetCustomerPasswordRepository.ts
  modules/customer/services/useResetCustomerPassword.ts
  modules/demo-magento/pages/confirm-password-reset.vue
  modules/theme-tailwind/templates/ConfirmPasswordReset.vue
  modules/theme-tailwind/templates/ResetPassword.vue
Labels: enhancement

#255 Add documentation for creation of simple TODO app
  docs/.vitepress/config.js
  docs/assets/simple-todo-app/1.png
  docs/assets/simple-todo-app/2.png
  docs/assets/simple-todo-app/3.png
  docs/assets/simple-todo-app/4.png
  docs/assets/simple-todo-app/5.png
  docs/guide/simple-todo-app.md
Labels: documentation

#259 Use page.locator in Playwright tests
  modules/base/tests/playwright/Public.spec.js
  modules/base/tests/playwright/Redirect.spec.js
  modules/base/tests/playwright/ServerRoutes.spec.js
  modules/basic-auth/tests/playwright/BasicAuth.spec.js
  modules/cms-shopware/tests/playwright/CmsBlocks.spec.js
  modules/vue-i18n/tests/playwright/VUE_I18N_ROUTE_PATHS.spec.js
  modules/vue-i18n/tests/playwright/VueI18n.spec.js
  modules/vue-i18n/tests/playwright/storesProperties.spec.js
  modules/vue-pinia/tests/playwright/VuePinia.spec.js
  modules/vue-router-simple/tests/playwright/Pages.spec.js
  modules/vue-router-simple/tests/playwright/Params.spec.js
  modules/vue-router-simple/tests/playwright/isExactActive.spec.js
  modules/vue-router/tests/playwright/Pages.spec.js
  modules/vue-router/tests/playwright/Params.spec.js
  modules/vue/tests/playwright/Components.spec.js
  modules/vue/tests/playwright/Vue.spec.js
Labels: internal

#260 Improve introduction and quick start documentation pages
  docs/.vitepress/config.js
  docs/getting-started/cookbook.md
  docs/getting-started/how-it-works.md
  docs/getting-started/introduction.md
  docs/getting-started/quick-start.md
  docs/getting-started/simple-todo-app.md
  docs/guide/getting-started.md
  docs/guide/why-storefront-x.md
  docs/index.md
  docs/modules/atatus.md
  docs/modules/cookie-script.md
  docs/modules/google-analytics.md
  docs/modules/google-tag-manager.md
  docs/modules/magento.md
  docs/modules/shopware.md
  modules/theme-tailwind/templates/Blog.vue
Labels: documentation

#262 Improve documentation for Simple todo app and Cookbook
  docs/.vitepress/config.js
  docs/cookbook/create-new-module.md
  docs/cookbook/display-data-from-backend.md
  docs/cookbook/generating-concept.md
  docs/cookbook/ioc-concept.md
  docs/cookbook/override-component.md
  docs/essentials/best-practices.md
  docs/essentials/bootstrap.md
  docs/essentials/cli.md
  docs/essentials/concepts.md
  docs/essentials/dotenv.md
  docs/essentials/faq.md
  docs/essentials/functionalities.md
  docs/essentials/lazy-components.md
  docs/essentials/pwa.md
  docs/essentials/redirecting.md
  docs/essentials/sfx.md
  docs/getting-started/cookbook.md
  docs/getting-started/how-it-works.md
  docs/getting-started/quick-start.md
  docs/getting-started/simple-todo-app.md
  docs/modules/base.md
  docs/modules/vue.md
Labels: documentation

#261 Fix typos and and improve texts in documentation
  docs/.vitepress/config.js
  docs/contributing.md
  docs/cookbook/create-new-module.md
  docs/cookbook/display-data-from-backend.md
  docs/cookbook/generating-concept.md
  docs/cookbook/ioc-concept.md
  docs/cookbook/override-component.md
  docs/essentials/best-practices.md
  docs/essentials/bootstrap.md
  docs/essentials/cli.md
  docs/essentials/concepts.md
  docs/essentials/faq.md
  docs/essentials/functionalities.md
  docs/essentials/lazy-components.md
  docs/essentials/pwa.md
  docs/essentials/redirecting.md
  docs/essentials/sfx.md
  docs/getting-started/how-it-works.md
  docs/getting-started/introduction.md
  docs/getting-started/quick-start.md
  docs/getting-started/simple-todo-app.md
  docs/integrations/magento.md
  docs/integrations/shopware.md
  docs/modules/atatus.md
  docs/modules/atomic-design.md
  docs/modules/base-commerce.md
  docs/modules/base.md
  docs/modules/basic-auth.md
  docs/modules/cart.md
  docs/modules/catalog.md
  docs/modules/cookie-script.md
  docs/modules/google-analytics.md
  docs/modules/google-tag-manager.md
  docs/modules/graphql.md
  docs/modules/magento.md
  docs/modules/multicurrency.md
  docs/modules/nprogress.md
  docs/modules/shopware.md
  docs/modules/theme-tailwind.md
  docs/modules/vue-i18n.md
  docs/modules/vue-pinia.md
  docs/modules/vue-router.md
  docs/modules/vue.md
Labels: documentation

#265 Add Routing page to the documentation
  docs/.vitepress/config.js
  docs/advanced/best-practices.md
  docs/advanced/bootstrap.md
  docs/advanced/concepts.md
  docs/advanced/dotenv.md
  docs/advanced/functionalities.md
  docs/advanced/lazy-components.md
  docs/advanced/pwa.md
  docs/essentials/redirecting.md
  docs/essentials/routing.md
  docs/getting-started/quick-start.md
  docs/modules/base.md
  docs/modules/vue.md
Labels: documentation

#246 Improve out of stock visualization
  modules/theme-tailwind-magento/molecules/AddToCart.vue
  modules/theme-tailwind/atoms/StockIndicator.vue
Labels: enhancement

#268 Add 'Why not' chapter to documentation
  docs/getting-started/introduction.md
Labels: documentation

#271 Add support for Magento cache tags
  .yarn/cache/data-uri-to-buffer-npm-4.0.0-e7a49f58f7-a010653869.zip
  .yarn/cache/fetch-blob-npm-3.2.0-28e01becfc-f19bc28a2a.zip
  .yarn/cache/formdata-polyfill-npm-4.0.10-e03013c013-82a34df292.zip
  .yarn/cache/node-domexception-npm-1.0.0-e1e813b76f-ee1d37dd2a.zip
  .yarn/cache/node-fetch-npm-3.3.0-45d971325c-e9936908d2.zip
  .yarn/cache/web-streams-polyfill-npm-3.2.1-835bd3857e-b119c78574.zip
  docs/contributing.md
  docs/getting-started/quick-start.md
  docs/modules/magento.md
  modules/core/package.json
  modules/core/src/Core.js
  modules/customer-magento/magento/beforeRequest/useCustomerMagentoRequestHeaders.ts
  modules/cypress/package.json
  modules/magento/composables/useMagento.ts
  modules/magento/concepts/MagentoAfterResponse.js
  modules/magento/concepts/MagentoBeforeRequest.js
  modules/magento/magento/afterResponse/useCollectCacheTags.server.ts
  modules/magento/tests/playwright/ModuleCombinations.spec.js
  package.json
  yarn.lock
Labels: enhancement

#273 Fix grand total price in order summary
  modules/cart-magento/mappers/ToCartPrices.ts
  modules/cart/composables/useCart.ts
  modules/checkout/composables/useCheckout.ts
  modules/checkout/stores/useCheckoutStore.ts
Labels: bug

#233 Improve product detail page of configurable products
  modules/catalog-magento/composables/useProduct.ts
  modules/catalog-magento/graphql/fragments/ConfigurableProduct.ts
  modules/theme-tailwind-magento/molecules/AddToCart.vue
  modules/theme-tailwind/molecules/FormRadioBox.vue
  modules/theme-tailwind/molecules/ProductConfigurableOption.vue
  modules/theme-tailwind/molecules/ProductConfigurableOptions.vue
Labels: enhancement

#286 Add fallback for meta titles
  modules/blog-magento/mappers/ToBlogPost.ts
  modules/catalog-magento/mappers/ToCategory.ts
  modules/catalog-magento/mappers/ToProduct.ts
  modules/cms-magento/mappers/ToCmsPage.ts
Labels: enhancement

#266 Hide empty product attributes
  modules/catalog-attributes-magento/mappers/ToProduct.ext.ts
  modules/theme-tailwind-magento-px/molecules/ProductAttributes.vue
Labels: bug

#267 Add PR template
  .github/pull_request_template.md
Labels: internal

#282 Add Cypress test for coupons
  modules/demo-magento/cypress/integration/checkout.js
  modules/demo-px/cypress/integration/category.js
  modules/demo-px/cypress/integration/checkout.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/base/expectNotificationReviewConfirm.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/base/getNotificationToast.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/checkout/getAddCouponButton.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/checkout/getAppliedCoupons.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/checkout/getApplyCouponButton.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/checkout/getCouponCodeInput.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/checkout/getRemoveCouponButton.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/checkout/removeCoupon.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/checkout/setCoupon.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/listing/getListProductCount.js
  modules/theme-tailwind-magento/molecules/Coupons.vue
  modules/theme-tailwind-shopware/cypress/support/pageObjects/base/expectNotificationReviewConfirm.js
  modules/theme-tailwind-shopware/cypress/support/pageObjects/base/getNotificationToast.js
Labels: internal

#292 Add test for two orders
  modules/demo-px/cypress/integration/checkout.js
Labels: internal

#296 Add build on demand
  .github/workflows/mxcloud.yml
  modules/demo-magento/config/MAGENTO_URL.ts
  modules/demo-px/config/MAGENTO_URL.ts
Labels: internal

#293 Add Event Bus documentation
  docs/.vitepress/config.js
  docs/advanced/event-bus.md
Labels: documentation

#290 Add support for X-Magento-Cache-Id
  modules/magento/magento/afterResponse/useGetCacheId.ts
  modules/magento/magento/beforeRequest/useSetCacheId.ts
Labels: enhancement

#303 Use bus concept for route navigation events
  docs/modules/base-commerce.md
  modules/nprogress/bus/listeners/useListenNavigationEnd.ts
  modules/nprogress/bus/listeners/useListenNavigationStart.ts
  modules/nprogress/vue/providers/NprogressProvider.vue
  modules/vue-router-simple/bus/events/NavigationEnd.ts
  modules/vue-router-simple/bus/events/NavigationStart.ts
  modules/vue-router-simple/components/SfxAppOutlet.vue
  modules/vue-router/bus/events/NavigationEnd.ts
  modules/vue-router/bus/events/NavigationStart.ts
  modules/vue-router/components/SfxLayoutOutlet.vue
  modules/vue/composables/useEventBus.ts
  modules/vue/concepts/BusEmitters.js
  modules/vue/concepts/BusEvents.js
  modules/vue/concepts/BusListeners.js
  modules/vue/tests/unit/composables/useEventBus.spec.js
Labels: internal

#306 Fixe reset password pages for native Magento
  modules/create-storefront-x/template/px/modules/demo-px/pages/confirm-password-reset.vue
  modules/demo-magento/pages/customer/account/createPassword/index.vue
  modules/demo-px/pages/confirm-password-reset.vue
  modules/demo-px/pages/customer/account/createPassword/index.vue
  modules/theme-tailwind/templates/CreatePassword.vue
Labels: bug

#276 Initialize cart on the client
  modules/cart-magento/composables/useCartToken.ts
  modules/cart-magento/config/MAGENTO_CART_COOKIE_NAME.ts
  modules/cart-magento/magento/errorHandlers/handleInvalidCart.ts
  modules/cart-magento/services/useGetOrCreateCartId.ts
  modules/cart-magento/services/useLoginCustomer.ext.ts
  modules/cart-magento/services/useMergeCarts.ts
  modules/cart-magento/stores/useCartMagentoStore.clientInit.ts
  modules/checkout-magento/services/useLoginCustomerInCheckout.ts
  modules/checkout-magento/services/usePlaceOrder.ts
  modules/customer-magento/composables/useCustomerToken.ts
  modules/customer-magento/config/MAGENTO_CUSTOMER_COOKIE_NAME.ts
  modules/customer-magento/magento/errorHandlers/handleAuthorizationError.ts
  modules/customer-magento/services/useLoginCustomer.ts
  modules/customer-magento/services/useLogoutCustomer.ts
  modules/customer-magento/stores/useCustomerMagentoStore.serverInit.ts
  modules/theme-tailwind/molecules/MicroCart.vue
  modules/vue-pinia/utils/vuePinia/waitForStore.ts
  modules/vue/components/ClientOnly.ts
Labels: enhancement

#308 Fix gallery for product variants to respect variant image
  modules/catalog-magento/composables/useProduct.ts
  modules/theme-tailwind-magento/molecules/CategoryButton.vue
  modules/theme-tailwind-magento/molecules/ProductTile.vue
  modules/theme-tailwind-magento/templates/BrandDetail.vue
  modules/theme-tailwind/molecules/HeaderMenu/FlyoutMenuSubCategory.vue
  modules/theme-tailwind/molecules/HeaderMenu/HamburgerMenuLink.vue
  modules/theme-tailwind/molecules/ProductGallery.vue
Labels: bug
