Repository storefront-x/storefront-x, pull requests merged in 2023-06, with the labels that each got.

#432 Use lefthook instead of husky
  .husky/pre-commit
  .lintstagedrc.json
  lefthook.yml
  modules/tooling/package.json
  package.json
  yarn.lock
Labels: enhancement, breaking

#437 Fixed Wishlists query cantBeCached
  modules/wishlist-magento/graphql/queries/Wishlists.ts
Labels: bug

#438 AddToWishlist rewrite to script setup
  modules/theme-tailwind/molecules/AddToWishlist.vue
Labels: enhancement
