Repository storefront-x/storefront-x, pull requests merged in 2023-05, with the labels that each got.

#421 Fix nested server routes
  modules/base/tests/playwright/ServerRoutes.spec.js
  modules/core/src/Dev.js
  modules/core/src/Serve.js
Labels: bug

#423 Fixed useResource ident refactoring
  modules/vue/composables/useId.ts
  modules/vue/composables/useResource.ts
Labels: bug

#424 Added rootMargin for IntersectionObserver in hydrateWhenVisible
  modules/vue/utils/hydration/hydrateWhenVisible.ts
Labels: enhancement

#425 Allow concept overriding
  modules/core/src/Build.js
  modules/core/src/Core.js
  modules/core/src/Module.js
  modules/core/tests/playwright/ConceptOverriding.spec.js
  modules/vue/concepts/BusEmitters.js
Labels: enhancement

#429 Add support for recursive global styles
  modules/base/concepts/GlobalStyles.js
  modules/base/tests/playwright/GlobalStyles.spec.js
Labels: enhancement

#430 Allow running multiple dev instances at the same time
  modules/core/package.json
  modules/core/src/Dev.js
  yarn.lock
Labels: bug

#428 Upgrade dependencies
  modules/atatus-server/package.json
  modules/base-commerce/package.json
  modules/braintree/package.json
  modules/cms-magento/package.json
  modules/core/package.json
  modules/core/sfx.js
  modules/create-storefront-x/package.json
  modules/cypress/package.json
  modules/partytown/package.json
  modules/sentry-client/package.json
  modules/sentry-server/package.json
  modules/service-worker/package.json
  modules/testing/package.json
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/setProductQuantityInputFromMinicart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/storeSwitcher/selectDifferentStoreOnMobile.js
  modules/theme-tailwind/package.json
  modules/tooling/package.json
  modules/vue-head/package.json
  modules/vue-pinia/package.json
  modules/vue-router/package.json
  modules/vue/package.json
  package.json
  yarn.lock
Labels: internal

#431 Upgrade dependencies
  modules/tooling/package.json
  modules/vue-i18n/package.json
  modules/vue-i18n/vite.config.js
  modules/vue/vite.config.js
  yarn.lock
Labels: internal
