Repository storefront-x/storefront-x, pull requests merged in 2023-09, with the labels that each got.

#449 Improve typing and error handling of useResource
  modules/vue/composables/useResource.ts
Labels: enhancement

#452 Upgrade vue-i18n & @intlify/unplugin-vue-i18n to stable versions
  modules/vue-i18n/package.json
  yarn.lock
Labels: enhancement

#451 Change pageKey to fullPath & make it configurable
  modules/vue-router/components/SfxPageOutlet.ts
Labels: enhancement

#453 Add build-time-version module
  modules/build-time-version/config/BUILD_TIME_VERSION.ts
  modules/build-time-version/package.json
  modules/build-time-version/tests/playwright/BuildTimeVersion.spec.js
  modules/build-time-version/vite.config.js
  modules/create-storefront-x/template/magento/package.json
  modules/create-storefront-x/template/magento/storefront-x.config.js
  modules/create-storefront-x/template/px/package.json
  modules/create-storefront-x/template/px/storefront-x.config.js
  yarn.lock
Labels: enhancement

#455 Fix generated types for SfxForm and SfxInput
  modules/base-commerce/components/SfxForm.vue
  modules/base-commerce/components/SfxInput.vue
Labels: bug

#456 Upgrade deps
  modules/core/package.json
  modules/cypress/package.json
  yarn.lock
Labels: internal
