Repository storefront-x/storefront-x, pull requests merged in 2023-03, with the labels that each got.

#387 Add Cypress tests for microcart
  modules/create-storefront-x/template/magento/modules/demo-magento/cypress/e2e/miniCart.cy.js
  modules/create-storefront-x/template/px/modules/demo-px/cypress/e2e/miniCart.cy.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/decreaseProductQuantityFromMinicart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/getProductFromMinicart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/getProductPriceFromMinicart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/getProductTitleFromMinicart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/increaseProductQuantityFromMinicart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/keepProductInCheckoutFromRemovalModal.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/removeProductFromCheckoutFromRemovalModal.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/removeProductFromMinicart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/minicart/setProductQuantityInputFromMinicart.js
  modules/theme-tailwind-magento/cypress/support/pageObjects/product/continueShopping.js
  modules/theme-tailwind/molecules/MiniCartItem.vue
  modules/theme-tailwind/organisms/ConfirmProductRemovalModal.vue
Labels: enhancement

#391 Don't remove Magento tags on no-cache
  modules/magento/magento/afterResponse/useCollectCacheTags.server.ts
Labels: internal

#395 Add extensions to GeneratingConcept
  modules/base/concepts/GlobalStyles.js
  modules/base/concepts/ServerStartup.js
  modules/base/concepts/TestsUnit.js
  modules/core/index.js
  modules/core/src/ExtendingConcept.js
  modules/core/src/GeneratingConcept.js
  modules/core/src/IocConcept.js
  modules/core/src/OverridingConcept.js
  modules/core/src/WatchingConcept.js
  modules/core/tests/playwright/GeneratingConcept.spec.js
  modules/cypress/concepts/CypressCommands.js
  modules/cypress/concepts/CypressE2E.js
  modules/cypress/concepts/CypressPageObjects.js
  modules/cypress/concepts/CypressRepositories.js
  modules/magento/concepts/MagentoDynamicPages.js
Labels: enhancement

#398 Removed npm from documentation
  docs/cookbook/create-new-module.md
  docs/getting-started/quick-start.md
  docs/getting-started/simple-todo-app.md
  modules/core/make/module.js
  modules/core/src/Module.js
  modules/create-storefront-x/index.js
Labels: documentation

#396 Added documentation for extendingConcept
  docs/advanced/concepts.md
  docs/assets/images/concept-hierarchy.png
Labels: documentation

#401 Add env var for Lets Encrypt certificates
  mxcloud/docker-compose.mxcloud.yml
Labels: internal

#402 Fix build & serve commands when used over NPM
  .github/workflows/core.yml
  docs/cookbook/create-new-module.md
  docs/getting-started/quick-start.md
  docs/getting-started/simple-todo-app.md
  modules/core/make/module.js
  modules/core/src/Module.js
  modules/create-storefront-x/index.js
  modules/vue/vite.config.js
Labels: bug

#405 Improved product labels fragment extension
  modules/catalog-labels-magento/graphql/fragments/Product.ext.ts
  modules/catalog-labels-magento/graphql/fragments/ProductInListing.ext.ts
Labels: enhancement

#400 Added support for mobile image in PB banner
  modules/cms-magento/composables/cms/usePbBanner.ts
  modules/cms-magento/composables/cms/usePbBlock.ts
  modules/cms-magento/composables/cms/usePbRow.ts
  modules/theme-tailwind-magento/magento/cms/blocks/pb-banner.vue
Labels: enhancement

#404 Added debug-tools startup check for Node version
  docs/modules/debug-tools.md
  modules/debug-tools/package.json
  modules/debug-tools/server/startup/debugTools.ts
Labels: enhancement

#403 Fixed error handling
  modules/cart-magento/vue/errorHandlers/handleCartResetted.ext.ts
  modules/cart/vue/errorHandlers/handleCartResetted.ts
  modules/cart/vue/errorHandlers/handleCustomerNotAuthorized.ext.ts
  modules/checkout/vue/errorHandlers/handleCustomerNotAuthorized.ext.ts
  modules/core/src/Core.js
  modules/create-storefront-x/template/magento/modules/demo-magento/cypress/e2e/account.cy.js
  modules/create-storefront-x/template/px/modules/demo-px/cypress/e2e/account.cy.js
  modules/customer-magento/vue/errorHandlers/handleCustomerNotAuthorized.ext.ts
  modules/customer/i18n/messages/cs-CZ.json
  modules/customer/i18n/messages/en-US.json
  modules/customer/vue/errorHandlers/handleCustomerNotAuthorized.ts
  modules/customer/vue/errorHandlers/handleCustomerNotVerified.client.ts
  modules/customer/vue/errorHandlers/handleCustomerNotVerified.server.ts
  modules/theme-tailwind/vue/errorHandlers/handleCustomerNotAuthorized.ts
  modules/vue/components/SfxVueProviders.vue
  modules/vue/vue/providers/ErrorHandlersProvider.client.vue
  modules/vue/vue/providers/ErrorHandlersProvider.server.vue
Labels: bug

#390 Added fallback for CMS page title, refactoring head on pages
  modules/blog-magento/mappers/ToBlogCategory.ts
  modules/blog-magento/mappers/ToBlogPost.ts
  modules/blog/composables/useBlogPost.ts
  modules/catalog-magento/mappers/ToCategory.ts
  modules/catalog-magento/mappers/ToProduct.ts
  modules/cms-magento/mappers/ToCmsPage.ts
  modules/create-storefront-x/template/px/modules/demo-px/magento/dynamicPages/AMASTY_BLOG_CATEGORY.vue
  modules/theme-tailwind/templates/BaseLayout.vue
  modules/theme-tailwind/templates/BlogPostDetail.vue
  modules/theme-tailwind/templates/CategoryDetail.vue
  modules/theme-tailwind/templates/CmsPage.vue
  modules/theme-tailwind/templates/ProductDetail.vue
Labels: enhancement

#406 Load .env file during MxCloud build
  mxcloud/docker-compose.mxcloud.yml
Labels: internal

#408 Added pre-commit check for max length of branch name
  .husky/pre-commit
Labels: enhancement

#409 Added MAGENTO_URL in magento-demo to lead to vanilla BE
  modules/catalog-magento/cypress/support/repositories/GetRandomCategory.js
  modules/catalog-magento/graphql/queries/CategoriesWithProductTypes.ts
  modules/create-storefront-x/template/magento/modules/demo-magento/config/MAGENTO_URL.ts
  modules/create-storefront-x/template/magento/modules/demo-magento/config/VUE_I18N_LOCALES.ts
  modules/create-storefront-x/template/magento/modules/demo-magento/cypress/e2e/checkout.cy.js
  modules/create-storefront-x/template/magento/modules/demo-magento/cypress/e2e/multicurrency.cy.js
  modules/create-storefront-x/template/magento/modules/demo-magento/cypress/e2e/product.cy.js
Labels: enhancement

#412 Fixed brand attribute config naming and position
  modules/brands-magento/config/brands-magento/ATTRIBUTE_NAME.ts
  modules/brands-magento/graphql/queries/BrandDetail.ts
  modules/brands-magento/repositories/useGetBrandDetailByIdRepository.ts
  modules/create-storefront-x/template/px/modules/demo-px/config/BRAND_ATTRIBUTE_NAME.ts
Labels: enhancement
