Repository storefront-x/storefront-x, pull requests merged in 2023-04, with the labels that each got.

#388 Migrate to H3
  docs/modules/base.md
  modules/base-commerce/package.json
  modules/base-commerce/server/routes/_i.js
  modules/base-commerce/server/routes/_i/[...].ts
  modules/base/tests/playwright/Config.spec.js
  modules/base/tests/playwright/IocConcept.spec.js
  modules/base/tests/playwright/ModulesOrder.spec.js
  modules/base/tests/playwright/ServerMiddleware.spec.js
  modules/base/tests/playwright/ServerRoutes.spec.js
  modules/base/types/base/Context.ts
  modules/cookie-auth/server/middleware/cookieAuth.ts
  modules/core/package.json
  modules/core/sfx.js
  modules/core/src/Core.js
  modules/core/src/Dev.js
  modules/core/src/Serve.js
  modules/core/tests/playwright/GeneratingConcept.spec.js
  modules/magento/magento/afterResponse/useCollectCacheTags.server.ts
  modules/magento/package.json
  modules/magento/server/routes/_magento.ts
  modules/magento/server/routes/_magento/[...].ts
  modules/request-profiler/vue/plugins/requestProfiler.server.ts
  modules/sitemap/server/routes/[prefix]/sitemap.xml.ts
  modules/sitemap/server/routes/sitemap.xml.ts
  modules/sitemap/tests/playwright/Sitemap.spec.js
  modules/testing/index.js
  modules/vue-i18n/types/sitemap/Options.ext.ts
  modules/vue-i18n/vue/plugins/vueI18n.ts
  modules/vue-router/vue/plugins/vueRouter.server.ts
  modules/vue/composables/useCookies.ts
  modules/vue/tests/playwright/useAsyncData.spec.js
  modules/web-app-manifest/server/routes/manifest.webmanifest.ts
  modules/web-app-manifest/tests/playwright/ModuleCombinations.spec.js
  modules/web-app-manifest/tests/playwright/WebAppManifest.spec.js
  yarn.lock
Labels: breaking

#414 Load MAGENTO_URL during runtime
  modules/create-storefront-x/template/magento/modules/demo-magento/config/MAGENTO_URL.ts
  modules/create-storefront-x/template/magento/modules/demo-magento/runtime/config/MAGENTO_URL.ts
  modules/create-storefront-x/template/magento/package.json
  modules/create-storefront-x/template/magento/storefront-x.config.js
  modules/create-storefront-x/template/px/modules/demo-px/config/MAGENTO_URL.ts
  modules/create-storefront-x/template/px/modules/demo-px/runtime/config/MAGENTO_URL.ts
  modules/create-storefront-x/template/px/package.json
  modules/create-storefront-x/template/px/storefront-x.config.js
  modules/runtime-config/utils/getRuntimeConfigValue.ts
Labels: internal

#410 Fixed styling and functionality of bundle product
  docs/modules/graphql.md
  modules/brands-magento/graphql/fragments/ProductInListing.ext.ts
  modules/cart-magento/repositories/useAddBundleProductToCartRepository.ts
  modules/catalog-magento-px/graphql/fragments/Product.ext.ts
  modules/catalog-magento-px/graphql/fragments/ProductInListing.ext.ts
  modules/catalog-magento/composables/useProduct.ts
  modules/catalog-magento/graphql/fragments/BundleItem.ts
  modules/catalog-magento/mappers/ToBundleOption.ts
  modules/catalog-magento/mappers/ToProduct.ts
  modules/graphql/tests/unit/utils/graphql/addFields.spec.js
  modules/graphql/utils/graphql/addFields.ts
  modules/product-reviews-magento/graphql/fragments/ProductInListing.ext.ts
  modules/theme-tailwind-magento/molecules/AddToCart.vue
  modules/theme-tailwind-magento/molecules/ProductBundlePrice.vue
  modules/theme-tailwind-magento/molecules/ProductTile.vue
  modules/theme-tailwind-magento/organisms/ProductOverview.vue
  modules/theme-tailwind/molecules/FormSelect.vue
  modules/theme-tailwind/molecules/ProductBundleOptions.vue
Labels: enhancement

#418 Removed gift_image svg to improve perf
  modules/create-storefront-x/template/magento/modules/demo-magento/public/images/gift_image.svg
  modules/create-storefront-x/template/px/modules/demo-px/public/images/gift_image.svg
  modules/theme-tailwind-magento-px/atoms/GiftPanel.vue
  modules/theme-tailwind/atoms/GiftPanel.vue
Labels: enhancement
