Repository storefront-x/storefront-x, pull requests merged in 2024-01, with the labels that each got.

#463 Cookies are shared per request on the server side
  modules/vue/composables/useCookies.ts
  modules/vue/tests/playwright/useCookies.spec.js
Labels: bug

#464 Fix i18n message interpolation in production
  modules/vue-i18n/tests/playwright/I18nMessages.spec.js
  modules/vue-i18n/vite.config.js
Labels: bug

#465 Add refetch to useResource
  modules/vue/composables/useResource.ts
  modules/vue/tests/playwright/useResource.spec.js
Labels: enhancement

#467 Add possibility to override MxCloud url
  .github/workflows/mxcloud.yml
Labels: internal
